name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: yarn install

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Run tests
      run: yarn test

    - name: Run automated release process with semantic-release
      if: github.ref_name == 'main'
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
